- hosts: all
  become: yes
  tasks:
    - name: Change user password
      user:
       name: "{{ user }}"
       update_password: always
       password: "{{ newpassword|password_hash('sha512') }}"
      
  #usage: ansible-playbook playbooks/update_local_user_pwd.yml -e newpassword=+Esadfdda -e user=john -i inventory
