version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-sandbox
    ports:
      - 9090:9090
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-sandbox
    ports:
      - 3000:3000
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge
